app/urls.py
# app/urls.py

from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('imc/', views.imc, name='imc'),
]

saude_e_cuidados/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'app/index.html')

def imc(request):
    return render(request, 'app/imc.html')

app/templates/app/imc.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div>
    <div>
        <h3>Calculadora</h3>

        <div>
            <label for="altura">Altura (m): </label>
            <input type="text" id="altura" name="altura" maxlength="4">
        </div>

        <div class="form-group">
            <label for="peso">Peso (kg): </label>
            <input type="text" id="peso" name="peso" maxlength="6">
        </div>
        <button name="calcular" onclick="calcularIMC()">Calcular</button>
        <div id="resultado" class="resultado"></div>
    </div>
</div>
{% endblock %}

{% block extra_script %}
<script src="{% static 'app/js/calculadora-imc.js' %}"></script>
{% endblock %}

app/templates/app/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div>
    <h1>Bem-vindo ao site de Saúde e Cuidados!</h1>
    <p>Saúde e cuidados pessoais são essenciais para uma vida equilibrada e saudável. Uma ferramenta valiosa nesse
        processo de autocuidado é o Índice de Massa Corporal (IMC), que você pode calcular facilmente clicando no botão
        abaixo.</p>
    <a href="{% url 'app:imc' %}" class="button">Calculadora de IMC</a>
</div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Saúde e Cuidados</title>
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
</head>

<body>
    <header>
        <nav>
            <div class="container">
                <h1><a href="{% url 'app:index' %}">Saúde e Cuidados</a></h1>
            </div>
        </nav>
    </header>

    <main>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </main>
</body>
{% block extra_script %}{% endblock %}

</html>